### ISSUE TITLE
Transcript problems with GRCh38

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/gene.iobio#619] opened 2020-09-04 20:20 UTC
Here is a link to GRCh38 file in gene COL9A3.

https://gene.iobio.io/?gene=COL9A3&genes=COL9A3&species=Human&build=GRCh38&affectedSibs=&unaffectedSibs=&rel0=proband&vcf0=https%3A%2F%2Fiobio.s3.amazonaws.com%2Fsamples%2Fvcf%2Fplatinum-exome.GRCh38.vcf.gz&tbi0=&bam0=https%3A%2F%2Fiobio.s3.amazonaws.com%2Fsamples%2Fbam%2FNA12878.GRCh38.bam&bai0=&sample0=NA12878&affectedStatus0=affected

1. When you land all the variants are gray. There is no impact assigned to any variant
2. Click on the transcript dropdown - lots of unnecessary whitespace and if you scroll down through the transcripts there are gaps which I don't understand

![Screen Shot 2020-09-04 at 4 11 28 PM](https://user-images.githubusercontent.com/523111/92281332-562f5080-eec9-11ea-90fa-407ea05ccb1f.png)

3. Click on the far left variant and you get this:

![Screen Shot 2020-09-04 at 4 14 12 PM](https://user-images.githubusercontent.com/523111/92281513-c5a54000-eec9-11ea-90c5-05bb1abfaeb1.png)

  - Under pathogenicity there are symbols that look like gray no entry signs. I don't know what they are supposed to represent (and they're not in the legend). Also, there is one with no text next to it, so I'm not sure what I'm supposed to do with that
  - The variant has no rsid number. We'll click on a different transcript in a moment, and you'll see this variant does have one, and this has no connection to the transcript

4. Click on a different transcript (you can just select one from the variant review card)
  - Focus on the variant is lost, so I have to go reselect it
  - Now you see there is an rsid

**Comment by WilliamRichards2017** [comment] 2020-09-14 17:28
Closing this issue and breaking it into two separate issues, as I'm not sure how to handle the null vep annotations for certain transcripts

**Comment by AlistairNWard** [comment] 2021-08-04 15:57
This still seems to be a problem, but maybe not something to worry about before paper release.

**Comment by AlistairNWard** [comment] 2022-05-04 17:20
Some of the issues appear to be resolved. What remains is:
1. Why are there no impacts on the canonical transcript?
2. Why does the far left variant have no rsid on the canonical trasncript?
3. Changing transcript loses focus on the selected variant - but the variant info remains

**Comment by tonydisera** [comment] 2022-07-20 16:09
The problem is that the canonical transcript for gene COL9A3 is incorrect. VEP is returning the annotations on variants for all transcripts of gene COL9A3, but the so-called canonical transcript 'ENST00000343916.7' is not included in VEP transcripts. This results in strange variant annotations in the Variant inspect card, like the ones mentioned above. 

So first, there should be an error reported that the transcript provided is not recognized by VEP. And second, we should re-load the transcripts for this gene to correct the transcript problem.  (See issue #164).

**Comment by AlistairNWard** [comment] 2022-07-20 16:23
MANE would be a nice way to help resolve this. The MANE transcript for COL9A3 is ENST00000649368.1 (NM_001853.4). Which is odd because the Ensembl id doesn't match up.

**Comment by AlistairNWard** [comment] 2022-07-20 16:30
Which is roundly rebuffed by Ensembl!!

<img width="1199" alt="Screen Shot 2022-07-20 at 12 30 23 PM" src="https://user-images.githubusercontent.com/523111/180034959-7a8c2010-751c-4e16-b96c-77fb7ffbcf6c.png">

**Comment by tonydisera** [comment] 2022-07-20 17:05
Interesting @AlistairNWard! Thanks for looking into this. I think I'll download the GenCode gff  (build GRCh38) and look at the transcripts for COL9A3. Let's hope that this has been fixed.

**Closed** 2023-01-05 20:50 UTC
Labels: bug
