### ISSUE TITLE
Reference is not being handled correctly

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/gene.iobio#1086] opened 2024-07-29 15:00 UTC
1. Launch gene.iobio for sample 15-0028470 family, gene WDR27 from https://mosaic.chpc.utah.edu/#/projects/1243/samples/
2. Mosaic shows this as a GRCh37 project, but gene.iobio is showing this as GRCh38
3. If I change the reference in gene.iobio to GRCh37, then I get told the gene is being reanalyzed, but the variant card is blank - no variants are shown
4. If I refresh, then the gene is reanalyzed and the coordinates change, but if I click the link to gnomAD, I'm taken to a GRCh38 page. Are all the annotations correct?

**Comment by tonydisera** [comment] 2024-07-29 21:00
I see slightly different behavior, but can replicate part of the bug you describe.

wrt #2 - When I launch gene.iobio from Mosaic for the project and sample specified, gene does correctly launch with genome build GRCh37 and shows the correct coordinates for WDR27. @AlistairNWard, can you confirm?
<img width="640" alt="Screenshot 2024-07-29 at 2 28 44 PM" src="https://github.com/user-attachments/assets/10da5c09-b266-448a-8b2b-842f76ce7730">


wrt 3 - When I switch back to GRCh37 (after first changing to GRCh38), I see the same problem: 0 variants and the wrong coordinates for the gene. If I click on the gene, this is corrected.
wrt #4 - I too see the incorrect link to gnomAD. (This is fixed in gene.iobio v4.11)

**Comment by tonydisera** [comment] 2024-07-29 21:01
So my plan is to fix the bug in v4.11 where toggling back to the previous build shows blank variants and the wrong gene coordinates.

**Comment by AlistairNWard** [comment] 2024-07-29 21:22
I don't know if things get cached, but I refresh, gene.iobio will load with GRCh38. I can close it and relaunch gene and sometimes it will launch in GRCh37, but it always goes back to GRCh38 eventually.

**Comment by tonydisera** [comment] 2024-07-29 21:26
Interesting. When it loads with GRCh38, what does the build URL parameter set to?

**Comment by AlistairNWard** [comment] 2024-07-29 21:37
https://gene.iobio.io/?source=https%3A%2F%2Fmosaic.chpc.utah.edu&project_id=1243&client_application_id=2&sample_id=61309&build=GRCh38&is_pedigree=true&gene=WDR27&genes=WDR27

**Comment by AlistairNWard** [comment] 2024-07-29 21:37
How are you getting the reference from Mosaic?

**Comment by tonydisera** [comment] 2024-07-29 21:39
@AlistairNWard I will consistently get the wrong URL parameter (build=GRCh38) with gene WDR27, but not every time. But when I select a different gene from the launch dialog, I get the correct URL parameter (build=GRCh37). Try gene MTHFR.

**Comment by tonydisera** [comment] 2024-07-29 21:55
> How are you getting the reference from Mosaic?
gene.iobio uses the genomeBuild.json to get the URL path to the fasta files based on the genome build. The genome build is a URL parameter filled in at runtime from Mosaic.

**Comment by AlistairNWard** [comment] 2024-07-30 13:33
Yes, but how are you getting the reference from Mosaic?

**Comment by tonydisera** [comment] 2024-07-31 14:38
@AlistairNWard, gene.iobio gets the build from the URL parameter, created from Mosaic when gene.iobio is launched. When you ask about the reference, are you referring to the gene coordinates, build, or fasta path? In all cases, these are determined from the build parameter, passed to gene.iobio from Mosaic via the url parameter.

I think there is a Mosaic bug here. At launch, sometimes the build=GRCh37, other times GRCh38. I haven't been able to isololate what causes the build parameter to vary, but I suspect it has something to do with the pedigree. When I launch gene.iobio from the Sample page, I consistently get build=GRCh37. When I launch from the Samples page (the individual sample is checked), the build will be set to GRCh37, but at some point, after multiple tabs are open, it switches to GRCh38 at launch time.

**Comment by tonydisera** [comment] 2024-07-31 14:57
If gene.iobio is launched from the 'Applications' page, the URL parameter build is set to GRCh37 consistently.

I can reproduce build=GRCh37 from the 'Samples' page if a previous launch of gene.iobio (in another tab) has undergone a build change to GRCh38.

**Comment by AlistairNWard** [comment] 2024-07-31 14:58
You build the url using the reference. My question is how, specifically you get the reference? I know you get it from mosaic, presumably using the mosaic api - but what is the command? Are you querying a specific attribute? Project settings? How are you getting the reference?

**Comment by tonydisera** [comment] 2024-07-31 21:37
1. gene.iobio uses the build (passed as a url parameter from Mosaic to gene.iobio) as a lookup to get to the full path of the fasta URL using the json genomeBuild.json.  
2. This JSON is a of the gene.iobio client-side file. The reference path is then sent from gene.iobio to the iobio gru backend via an argument to a bash script (e.g. annotateVariantsV2.sh). 
3. The iobio backend bash script executes various apps (e.g. VEP, freeBayes, etc.), passing in the fasta path as a command line argument.
4. The other way the build is used is to get the gene coordinates and transcripts. So gene.iobio uses the build to call the backend service geneinfo to get the gene coordinates and transcripts for a given gene, build, and source (refseq or gencode).

**Comment by tonydisera** [comment] 2024-07-31 21:38
Should we meet on this? I'm available for a quick zoom call any time you are available. I think there is a Mosaic bug at play here...

**Comment by AlistairNWard** [comment] 2024-08-01 00:38
We could meet. I'm clearly not asking my question clearly. I know you get the reference build from Mosaic, I'm just not sure how you get the reference build to put in the url

**Comment by tonydisera** [comment] 2024-08-01 04:26
Here is what the URL looks like when Mosaic launches gene.iobio:

`https://gene.iobio.io/#access_token=19b4ec7dafd87ff95ecc48e94ede59a57635b106&expires_in=3600&token_type=Bearer&source=https%3A%2F%2Fmosaic.chpc.utah.edu&project_id=1243&client_application_id=2&sample_id=61309&build=GRCh37&is_pedigree=true&gene=WDR27&genes=WDR27`

As for the mechanism to get the build from the URL, here are the coding details:
1. In gene.iobio (routes.js), there is generic javascript code to get the build URL parameter value using a library called qs.js (https://www.npmjs.com/package/qs). 
2. QueryString.parse will create an object with all the URL parameters. The code removes the token from the URL. Now the URL looks like this:
`https://gene.iobio.io/?source=https%3A%2F%2Fmosaic.chpc.utah.edu&project_id=1243&client_application_id=2&sample_id=61309&build=GRCh37&is_pedigree=true&gene=WDR27&genes=WDR27`

4. In routes.js, Vue.js has access to the URL parameters in the object routes.query. There is code that initializes a string paramBuild to the value in routes.query.build. Now gene.iobio has access to paramBuild, which contains the value **GRCh37** (from the URL above).

**Comment by AlistairNWard** [comment] 2024-08-01 12:17
I'm only interested in how Mosaic is providing the reference. So Mosaic is creating the url, so it's Mosaic using the api to get the reference build?

**Comment by tonydisera** [comment] 2024-08-04 22:07
I have added validation code to gene.iobio so that the user is warned when the vcf header assembly (or reference lengths) conflict with the specified build.

<img width="341" alt="Screenshot 2024-08-04 at 4 06 49 PM" src="https://github.com/user-attachments/assets/03931ef7-154f-4589-b67a-6e099b6337e7">

From the files dialog:
<img width="892" alt="Screenshot 2024-08-04 at 4 07 43 PM" src="https://github.com/user-attachments/assets/16be1181-23db-4c94-96b7-549eb52b333f">

**Comment by tonydisera** [comment] 2024-08-04 22:09
I've also fixed the bug so that when the users switches genome builds, the gene coordinates on the selected gene are correctly refreshed when the genes are reanalyzed.

**Comment by tonydisera** [comment] 2024-08-04 22:11
A separate issue should be entered in Mosaic to address the incorrect build parameter at launch time.

**Closed** 2024-08-13 21:11 UTC
Labels: bug
