### ISSUE TITLE
v4.7.1 Side-panel Bugs (progression and variant numbering)

### ISSUE THREAD

**Issue by Georgenetics** [iobio/gene.iobio#934] opened 2023-05-25 02:03 UTC
In the current web version, v.4.7.1, there are two main bugs in the side panel. The first is relatively simple, the variant count is put one gene down from where it should. See 
![gene variant count row down](https://github.com/iobio/gene.iobio/assets/134524671/4ea1a8c5-7802-4508-8d20-0bc70895eae4)

The second is a glitch with progression. With VCF files loaded and the gene phenotype generator set to 100 genes, it will not progress past the first gene. I've been running a set of genes for ~12 hours now, and it hasn't progressed since the first one. See 
![lack of gene progression](https://github.com/iobio/gene.iobio/assets/134524671/efc97437-36f1-4cee-9cc6-c21e676095f2)

**Comment by Georgenetics** [comment] 2023-05-25 20:06
@AlistairNWard Thank you for asking, I am running it with my own vcf file (I'm using an uploaded file, not a data url if that makes a difference). I've tried using different vcf files on my computer, this bug appears with each one. I'm getting 100 genes by going into the app settings in the header bar, and under "Keep top n genes from phenotype search" I use the dropdown to select 100. 
![number of genes allowed](https://github.com/iobio/gene.iobio/assets/134524671/39f7b125-105f-49a6-af57-3334a3745219)
From there I just use the phenotype box in the header to select a phenotype and the genes are loaded.
Thank you!!

**Comment by AlistairNWard** [comment] 2023-05-27 00:03
Ok, I've tried with a local vcf file and a url, set the number of genes to 100 and then put in a phenotype term and I can't replicate the behaviour of the number of variants aligning against the wrong gene. I do seem to get processing stuck though, so we can look into this to begin with

**Comment by tonydisera** [comment] 2023-06-01 20:21
@Georgenetics, I'm trying to replicate the error you are seeing. What browser are you running gene.iobio in? I don't see the problem with the variant count showing one gene down. I also don't see the problem where processing stops after the first gene. Would it be possible to send me your local vcf file? If that is not possible, would you be available to meet over a Zoom call so that I can try to troubleshoot remotely?
Best regards,
Tony Di Sera
Gene.iobio developer

**Comment by AlistairNWard** [comment] 2023-06-01 21:24
I tried again and got it to stuck on the first gene. Subsequent tests ran fine. When it was stuck, I saw "Websocket closing or in closed state' in the inspector.

**Comment by tonydisera** [comment] 2023-06-02 01:01
There wasn't an error or warning in the Notifications panel?

**Comment by AlistairNWard** [comment] 2023-06-02 16:55
I didn't see one, and now I can't get it to fail to check!

**Comment by Georgenetics** [comment] 2023-06-07 19:54
@tonydisera Sorry, I got locked out of my account last week. I tried attaching the compressed vcf files, but it says its to big here. I can send you those files another way, and I can do a zoom call whenever works for you. I'm using Chrome as my browser. Thank you!

**Comment by tonydisera** [comment] 2023-06-08 17:36
@Georgenetics, would it be possible for you to upload your vcf to your google drive and share it with me?
Thanks!
Tony

**Comment by Georgenetics** [comment] 2023-06-09 03:39
@tonydisera I can do that! Here is the link:
https://drive.google.com/drive/folders/1ZWdxu19hAYhUnFFQszKb5Q5_3rbYO1vw?usp=sharing
Thank you!

**Comment by tonydisera** [comment] 2023-06-09 18:39
Hi @Georgenetics. I can reproduce the problem on a large gene (RYR2). The request is timing out. So I will start looking into how to remedy this. I want to make sure that I am reproducing the same error. Would you please send me the gene list or the phenotype term you used to generate your gene list?
Thanks,
Tony

**Comment by tonydisera** [comment] 2023-06-09 19:59
After discussing with Anders, our backend expert, we are going to increase the timeout on our AWS EC2 load balancer from 60 sec to 120 sec. Also, we need to make sure that the timeout is reported back to the application. Right now, the backend error does not result in the iobio cmd handler for reporting errors.
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://backend.iobio.io/annotateVariantsV2. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 504.

**Comment by Georgenetics** [comment] 2023-06-21 01:17
@tonydisera That is great! Thank you! I've made a quick video showing what is happening on my end, taking into account what you've shared. Hopefully this helps!
https://photos.app.goo.gl/m2uzCrHJn3teqDEK9

**Comment by tonydisera** [comment] 2023-06-23 20:05
Thank you @Georgenetics. Your screencast was very helpful. I can reproduce the problem, although not every time. Also, the problem occurs further down in the gene list. I've provided a video here so you can compare it to your experience.

https://drive.google.com/file/d/1NB7jA0ZH3_9cc3WdoHGOQ4ZT9d8kPpUX/view?usp=sharing

Here are the results of a speed test. **_I'm curious how this compares to your internet speed._** This shouldn't be impacting the server timeout, but that can't be ruled out entirely. 

<img width="405" alt="Screenshot 2023-06-23 at 1 43 55 PM" src="https://github.com/iobio/gene.iobio/assets/8420103/60057b78-4a02-4252-8508-ac77fd327673">

For my screencast video, if you advance 2:55, you see that I right-click on the browser and click on **'Inspect'** from the menu. (I'm using the Chrome browser, but the same right-click menu option is available in Firefox.) In the 'Console' tab, you can see that there are a number of errors in red that indicate that the service annotateVariantsV2 is timing out. 

We need to make a few changes to our backend:
1. The timeout error is not getting properly reported back to the app. When this occurs, the app should be able to notify the user of the problem.
2. To prevent the timeout from occurring in the first place, we are going to bump up the timeout interval from 60 seconds to 120 seconds. That way, the app will be able to continue analyzing the data on genes with lots of variants.
3. We can also adjust our load balancer, increasing the number of instances. This will help when the many users are trying to analyze their data in gene.iobio at the same time. 

So right now, I'm going to change the server settings to see if gene.iobio can consistently analyze the 100 genes without getting stuck due to the timeout. 

I have not been able to figure out UI problem where the variant count shows up one gene down.  It shows up correctly for me on Chrome and Firefox. **_What browser and version you are running?_** 

I'll keep you posted when you can try out your analysis again.

Thanks!
Tony

**Comment by tonydisera** [comment] 2023-07-17 21:12
Hi @Georgenetics,

We have bumped up the number of backend servers running our IOBIO backend. I've tried your VCF, analyzing 100 genes, and it has completed without problems. Would you mind giving it a try?

Best regards,
Tony

**Comment by Georgenetics** [comment] 2023-07-17 22:24
@tonydisera I've just ran a couple of tests, and they are all working out beautifully! To answer some of your previous questions, I have 17MPs down and 5MPs up for my internet, and I've been running Chrome version Version 114.0.5735.199 as my browser. There is still the gene count down one glitch, but as it doesn't affect performance, I'm not that worried about it. Thank you for all the time you have put into helping me and making this amazing program!!

**Closed** 2023-09-04 00:15 UTC
