### ISSUE TITLE
Can't upload data

### ISSUE THREAD

**Issue by eclareaufromage** [iobio/gene.iobio#835] opened 2022-06-27 11:47 UTC
Hi all! Thanks for putting together such a great tool. 

As of the latest update, I'm unable to upload my data. I'm attempting to upload a VCF and its index file. I select the relevant species and genome build, but the load button remains greyed out and unresponsive. Have tried this several times using different browsers. The site always worked fine using the same variables, including the same files, before this update.

**Comment by AlistairNWard** [comment] 2022-06-27 13:13
Would you be able to include a screenshot of what you are seeing, and the options that you are selecting. That will help us debug the problem

**Comment by eclareaufromage** [comment] 2022-06-27 14:12
![Genome iobio io upload](https://user-images.githubusercontent.com/108274576/175961035-a16d8431-d594-4b3e-99f2-7681be85fa4b.png)
Yes! Here is a screenshot. What used to happen was that, a few seconds after selecting the files, species, and genome build, the Load button would illuminate and become clickable. My file would quickly load when I clicked. The button now remains greyed out indefinitely and is not clickable.

**Comment by Bmerry8** [comment] 2022-06-29 20:39
Hello, thank you for this very useful tool. I would just like to add that I am also having the same problem. When I select both the vcf.gz and vcf.gz.tbi files after clicking "choose files" for VCF, the Load button remains greyed out. I have also already selected species and genome build. I can get the load button to work by adding a CRAM file as well as the VCF and TBI, but no variants are displayed when I analyse genes or try to call variants after doing this. The software was working for me a few days ago but has now stopped working - it shows no variants on any genes (including genes which I know have many variants because I was looking at them just a few days ago). Thank you very much for your help and best wishes.

**Comment by AlistairNWard** [comment] 2022-06-29 22:06
It looks like this is a problem with the gene.iobio version associated with Nebula Genomics. We are working with them to understand the problem, and I’ll let you know when these issues are resolved. Sorry for the inconvenience

**Comment by tonydisera** [comment] 2022-06-29 22:53
@AlistairNWard, the user can't select the files in the Nebula version; only the public gene.iobio version. I confirmed that a local vcf and tbi file can be selected. It takes about 5 seconds to see the dropdown of the samples. If there is only one sample, the load button is enabled. I'm going to email the user to find out if the samples dropdown ever loads and find out why the user isn't going throug the Nebula website to access the vcf files.

**Comment by AlistairNWard** [comment] 2022-06-30 12:25
Good point @tonydisera . I confirmed that the local file load works on prod gene and asked the original user to confirm they were selecting the vcf and tbi simultaneously. It looks like the second user confirmed they were doing this correctly though, so looks like there is a different problem. I assume these aren’t Nebula users

**Comment by Bmerry8** [comment] 2022-06-30 13:44
Thank you very much for your replies @AlistairNWard and @tonydisera - I was referring to the public version not the Nebula version, but it seems to be working again for me now. Not sure why it wasn't working before but today it is letting me select and load VCF files fine. Thank you for your time and help!

**Comment by eclareaufromage** [comment] 2022-06-30 16:18
Hi, I'm sorry not to have gotten back to you sooner! 

Indeed I was selecting both a .vcf file and a .tbi file simultaneously. I don't use the version associated with Nebula Genomics, as my genome was sequenced by a different provider - I access https://[gene.iobio](https://gene.iobio.io/).io/ directly and upload files that I have saved locally.

As is the case for @Bmerry8, I have tried again and it now works fine. It's quite a curious problem since I see the code hasn't been updated, but glad to have it working again! Thanks @AlistairNWard and @tonydisera for your help!

**Comment by AlistairNWard** [comment] 2022-06-30 16:26
On the one hand, I'm glad that you're both able to access your data now, but it's never great to see these sporadic issues! Is it possible that your internet connection wasn't great when you experienced problems? Gene.iobio can be affected by poor a connection.

Regardless, I'll leave this issue open for now in case you see this problem again, but if I don't hear of any recurring problems, I'll close this in a week or so.

Thanks again for your feedback. We appreciate it!

**Comment by eclareaufromage** [comment] 2022-06-30 16:54
Yes, I'm sure you'd prefer to get to the bottom of it! 

I doubt it was network issues on my side. I had tried several times over the course of the day, and tried closing all other programs that might take up bandwidth. Throughout the rest of the day I was in video calls and working on documents in the cloud and didn't experience any problems with my connection.

**Comment by tonydisera** [comment] 2022-07-15 17:22
It isn't apparent to the user that the load button isn't enabled until a sample has been selected. This will be addressed with issue #837 which will show a loading gif by the samples dropdown indicating the samples are being retrieved from the file. Second, an error message should be returned when the samples dialog can't be loaded so that the user knows that a problem has occurred. Let's include this error message as part of #837. I will close this issue.

**Closed by tonydisera** 2022-07-15 17:22 UTC
Labels: User feedback
